/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasEpicas;

/**
 *
 * @author crist
 */
public class PrincipalFuncionesEpicas extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public PrincipalFuncionesEpicas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Tienda = new javax.swing.JLabel();
        SubTextHeader = new javax.swing.JLabel();
        ExitButton = new javax.swing.JLabel();
        Mid = new javax.swing.JPanel();
        OptionMidPanel = new javax.swing.JPanel();
        Inventario = new javax.swing.JPanel();
        InventarioImg = new javax.swing.JLabel();
        InventarioName = new javax.swing.JLabel();
        Venta = new javax.swing.JPanel();
        VentaImg = new javax.swing.JLabel();
        VentaName = new javax.swing.JLabel();
        Pedido = new javax.swing.JPanel();
        PedidoImg = new javax.swing.JLabel();
        PedidoName = new javax.swing.JLabel();
        Movimientos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaMovimientos = new javax.swing.JList<>();
        Reload = new javax.swing.JLabel();
        Foot = new javax.swing.JPanel();
        Configuration = new javax.swing.JLabel();
        Database = new javax.swing.JLabel();
        User = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(44, 62, 80));

        Tienda.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        Tienda.setForeground(new java.awt.Color(255, 255, 255));
        Tienda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tienda.setText("TIENDA");

        SubTextHeader.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        SubTextHeader.setForeground(new java.awt.Color(255, 255, 255));
        SubTextHeader.setText("Menu Principal");

        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancel_20px.png"))); // NOI18N
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubTextHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(586, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(ExitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubTextHeader))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        PanelPrincipal.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 110));

        Mid.setBackground(new java.awt.Color(236, 240, 241));

        OptionMidPanel.setBackground(new java.awt.Color(44, 62, 80));

        Inventario.setBackground(new java.awt.Color(189, 195, 199));
        Inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventarioMouseClicked(evt);
            }
        });

        InventarioImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Choice_80px.png"))); // NOI18N
        InventarioImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventarioImgMouseClicked(evt);
            }
        });

        InventarioName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        InventarioName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InventarioName.setText("Inventario");
        InventarioName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventarioNameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InventarioLayout = new javax.swing.GroupLayout(Inventario);
        Inventario.setLayout(InventarioLayout);
        InventarioLayout.setHorizontalGroup(
            InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioLayout.createSequentialGroup()
                .addGroup(InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InventarioLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(InventarioImg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InventarioLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(InventarioName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        InventarioLayout.setVerticalGroup(
            InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InventarioImg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InventarioName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Venta.setBackground(new java.awt.Color(189, 195, 199));
        Venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VentaMouseClicked(evt);
            }
        });

        VentaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buy_80px.png"))); // NOI18N
        VentaImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VentaImgMouseClicked(evt);
            }
        });

        VentaName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        VentaName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VentaName.setText("Venta");
        VentaName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VentaNameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VentaLayout = new javax.swing.GroupLayout(Venta);
        Venta.setLayout(VentaLayout);
        VentaLayout.setHorizontalGroup(
            VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentaLayout.createSequentialGroup()
                .addGroup(VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentaLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(VentaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VentaLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(VentaName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        VentaLayout.setVerticalGroup(
            VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VentaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VentaName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pedido.setBackground(new java.awt.Color(189, 195, 199));
        Pedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PedidoMouseClicked(evt);
            }
        });

        PedidoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/New Product_80px.png"))); // NOI18N
        PedidoImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PedidoImgMouseClicked(evt);
            }
        });

        PedidoName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        PedidoName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PedidoName.setText("Pedido");
        PedidoName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PedidoNameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PedidoLayout = new javax.swing.GroupLayout(Pedido);
        Pedido.setLayout(PedidoLayout);
        PedidoLayout.setHorizontalGroup(
            PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidoLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidoLayout.createSequentialGroup()
                        .addComponent(PedidoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidoLayout.createSequentialGroup()
                        .addComponent(PedidoName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        PedidoLayout.setVerticalGroup(
            PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PedidoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PedidoName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout OptionMidPanelLayout = new javax.swing.GroupLayout(OptionMidPanel);
        OptionMidPanel.setLayout(OptionMidPanelLayout);
        OptionMidPanelLayout.setHorizontalGroup(
            OptionMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionMidPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        OptionMidPanelLayout.setVerticalGroup(
            OptionMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionMidPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OptionMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Movimientos.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        Movimientos.setText("Ultimos movimientos");

        ListaMovimientos.setBackground(new java.awt.Color(189, 195, 199));
        jScrollPane1.setViewportView(ListaMovimientos);

        Reload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sync_25px.png"))); // NOI18N
        Reload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReloadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MidLayout = new javax.swing.GroupLayout(Mid);
        Mid.setLayout(MidLayout);
        MidLayout.setHorizontalGroup(
            MidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MidLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(OptionMidPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MidLayout.createSequentialGroup()
                        .addComponent(Movimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Reload, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        MidLayout.setVerticalGroup(
            MidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OptionMidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Movimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Reload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelPrincipal.add(Mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 920, 400));

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 520));

        Foot.setBackground(new java.awt.Color(44, 62, 80));
        Foot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Configuration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Settings_35px.png"))); // NOI18N
        Configuration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfigurationMouseClicked(evt);
            }
        });
        Foot.add(Configuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 35, 35));

        Database.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Database Administrator_35px.png"))); // NOI18N
        Database.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatabaseMouseClicked(evt);
            }
        });
        Foot.add(Database, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 35, 35));

        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User Location_35px.png"))); // NOI18N
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
        });
        Foot.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 35, 35));

        getContentPane().add(Foot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 920, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_ExitButtonMouseClicked

    // Inicio Funciones Inventario
    private void InventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventarioMouseClicked

    }//GEN-LAST:event_InventarioMouseClicked

    private void InventarioImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventarioImgMouseClicked

    }//GEN-LAST:event_InventarioImgMouseClicked

    private void InventarioNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventarioNameMouseClicked

    }//GEN-LAST:event_InventarioNameMouseClicked
    //Fin Funciones Inventario
    
    // Inicio Funciones Venta
    private void VentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentaMouseClicked
        
    }//GEN-LAST:event_VentaMouseClicked

    private void VentaImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentaImgMouseClicked
        
    }//GEN-LAST:event_VentaImgMouseClicked

    private void VentaNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentaNameMouseClicked
        
    }//GEN-LAST:event_VentaNameMouseClicked
    //Fin Funciones Venta
    
    // Inicio Funciones Pedido
    private void PedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PedidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PedidoMouseClicked

    private void PedidoImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PedidoImgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PedidoImgMouseClicked

    private void PedidoNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PedidoNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PedidoNameMouseClicked
    //Fin Funciones Pedido
    
    /* El siguiente metodo muestra la vista de configuracion de la base de datos*/
    private void DatabaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatabaseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DatabaseMouseClicked

    /* El siguiente metodo muestra la vista de la informacion de usuario que inicio sesion*/
    private void UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UserMouseClicked

    /* El siguiente metodo muestra configuraciones relacionadas con la vista principal*/
    private void ConfigurationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfigurationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfigurationMouseClicked

    /* El siguiente metodo recarga la funcion de la lista de acciones*/
    private void ReloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReloadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ReloadMouseClicked
   
    
    
   
   // Fin de Funciones Inventario
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFuncionesEpicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFuncionesEpicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFuncionesEpicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFuncionesEpicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFuncionesEpicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Configuration;
    private javax.swing.JLabel Database;
    private javax.swing.JLabel ExitButton;
    private javax.swing.JPanel Foot;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Inventario;
    private javax.swing.JLabel InventarioImg;
    private javax.swing.JLabel InventarioName;
    private javax.swing.JList<String> ListaMovimientos;
    private javax.swing.JPanel Mid;
    private javax.swing.JLabel Movimientos;
    private javax.swing.JPanel OptionMidPanel;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel Pedido;
    private javax.swing.JLabel PedidoImg;
    private javax.swing.JLabel PedidoName;
    private javax.swing.JLabel Reload;
    private javax.swing.JLabel SubTextHeader;
    private javax.swing.JLabel Tienda;
    private javax.swing.JLabel User;
    private javax.swing.JPanel Venta;
    private javax.swing.JLabel VentaImg;
    private javax.swing.JLabel VentaName;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
